spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: test1357
    # url: jdbc:h2:mem:test
#    username: sa
#    password:
#    username: sekwangoh
#    password: '{cipher}AQCLaq/JZ3GOL6SB7Ul0PH4NMYvCN+R9NZel7vuHebIPfN8XFaNHwlwbmfxf+k3F90zNoaBIwMwnZefGHydwDgbObsCPf5WKDnA8DWomQ6W1IcfJzAU2XrAtz3vSxN620pW4LmDoWqmS2C3kPhAblBuCZS4TGN1T8kzd5ZRXrlmyQACeWKyfCz4hidsZB/LPfOuxxLpD5vZsqpeCmqwDHhsnEacZlZxThASSDRAeAN5kWIXhYSRxq9DS48q6muxkZgBHA6k4x06046jkSILmXTep/4reGFkOgQHk6Epzxw2g2r+ciJ9Z8uuwqd437qMgrKwpCfQQmU8AFUc+k35w60SM+oSfb/3r54UXTZJg+rczBDnD5Sy7AQ8y5hMUjoZDbUk='

token:
  expiration_time: 86400000
  secret: '{cipher}AQA7vvoLDbSltUTM2mdTX2jSi67mj84swszkcIEBRHY7NTfTBqiHCkc2d9XHhBo5plCmheKtnzItklnnI1agDq40Vp3Z/0p9bOU/gnXUWWG7bqy2Cxx8SNphncG7Fb0vhtTSYRy1P+sFo6FC8RALCk/bNo4WlZ339uXEARllWVO0WVC4cx0YeaF0Sy/fLvAxWPZbg0fhwtGGhlvPKX8btbxs1AmihM3WvxUFjXBlzR3v3S8Ke93g7Weq/LRez7Y4k2sCtLDWNGtls0U137v1AZtYB0YxU5qqjtAagHUhfJnonjL8VhSon4gN2Tjz0ucgj/UEsUBOOnm98uTMoudp8lBWmTPpy15A/JDCQRQjf6npptLlJDAmusmLatcwmMHTH4S8k8gZUbSZ76OVk/Viqj/OQm0fb6yUx8Gs9abN1owjBKFISHdY4gpSqfoxi2f1gQ+OKkMtwWHxTz4ZfEuIlY8dCblQ12TxCYaqkVyvoGq/pWLAbPwC92kSRK/T9ApauOwhoBct1ShfLHJ/ekq7XRCANAX6S+vSkf6TDEqEvy9/9j6IFuLxOmx32H6GZt/cRRyvr8aCKKL7pIqpvT+mr/KFiChArbuHkckXu1NCZ/IkEJs/1HJdq3jjmUUJUiPHQyWaQhTnkztLJXHC2Y+BN8lHx0ih81r/AFG7eExqfUv0KMbLTd74OeZllSHRaky4rgaB3J2v9L7uatVrU4LXXAanIL010pRGMRIlhqLbaDSIKQwAFFVSzjucB9zqYtHHWhnPJZY0hc8oIJ8i79iLqF4PGav7iDosgHAbJmhIymY9ixHZPONJCHoNoaOWfffEgGJ8VibVJAR7KTyqZuldfiRkeAwtZztlhbs4eOaECu6c9o6LvfKy6KqSSEzrOYtvx1HG1Mp8zxxYApqbeRsFGJ2krm9Pl9i/ojzddygRDP6a/w=='

gateway:
  ip: 192.168.0.12

order_service:
  url: lb://ORDER-SERVICE/order-service/%s/orders